-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 22:52:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema agil
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agil` ;

-- -----------------------------------------------------
-- Schema agil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agil` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `agil` ;

-- -----------------------------------------------------
-- Table `agil`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agil`.`aluno` ;

CREATE TABLE IF NOT EXISTS `agil`.`aluno` (
  `id_usuario` INT(11) NOT NULL,
  `id_tipo_aluno` INT(11) NULL DEFAULT NULL,
  `flg_curso` CHAR(1) NULL DEFAULT NULL,
  `des_programa` VARCHAR(100) NULL DEFAULT NULL,
  `des_orientador` VARCHAR(45) NULL DEFAULT NULL,
  `des_nacionalidade` VARCHAR(45) NULL DEFAULT NULL,
  `dt_data_nas` DATE NULL DEFAULT NULL,
  `des_endereco` VARCHAR(350) NULL DEFAULT NULL,
  `des_nome_mae` VARCHAR(60) NULL DEFAULT NULL,
  `des_Instituicao` VARCHAR(60) NULL DEFAULT NULL,
  `des_curso` VARCHAR(60) NULL DEFAULT NULL,
  `num_matricula` INT(11) NULL DEFAULT NULL,
  `des_campus` VARCHAR(60) NULL DEFAULT NULL,
  `ano_conclusao` TINYINT(4) NULL DEFAULT NULL,
  `des_graduacao` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_id_tipo_aluno_idx` (`id_tipo_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_id_tipo_aluno`
    FOREIGN KEY (`id_tipo_aluno`)
    REFERENCES `agil`.`tipo_aluno` (`id_tipo_aluno`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_usuario_aluno`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `agil`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agil`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agil`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `agil`.`disciplina` (
  `id_disciplina` INT(11) NOT NULL AUTO_INCREMENT,
  `des_disciplina` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id_disciplina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agil`.`matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agil`.`matricula` ;

CREATE TABLE IF NOT EXISTS `agil`.`matricula` (
  `id_matricula` INT(11) NOT NULL AUTO_INCREMENT,
  `id_disciplina` INT(11) NULL DEFAULT NULL,
  `dt_data` DATE NULL DEFAULT NULL,
  `flg_outra_situacao` BIT(1) NOT NULL,
  `id_periodo` INT(11) NULL DEFAULT NULL,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `fk_id_disciplina_idx` (`id_disciplina` ASC) VISIBLE,
  INDEX `fk_id_periodo_idx` (`id_periodo` ASC) VISIBLE,
  INDEX `fk_id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_id_usuario_matricula_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_id_disciplina`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `agil`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_periodo`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `agil`.`periodo` (`id_periodo`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_usuario_matricula`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `agil`.`usuario` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agil`.`periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agil`.`periodo` ;

CREATE TABLE IF NOT EXISTS `agil`.`periodo` (
  `id_periodo` INT(11) NOT NULL AUTO_INCREMENT,
  `des_periodo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_periodo`),
  UNIQUE INDEX `des_periodo_UNIQUE` (`des_periodo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agil`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agil`.`tipo` ;

CREATE TABLE IF NOT EXISTS `agil`.`tipo` (
  `id_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` CHAR(1) NULL DEFAULT NULL,
  `des_tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo`),
  UNIQUE INDEX `id_tipo_UNIQUE` (`id_tipo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agil`.`tipo_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agil`.`tipo_aluno` ;

CREATE TABLE IF NOT EXISTS `agil`.`tipo_aluno` (
  `id_tipo_aluno` INT(11) NOT NULL AUTO_INCREMENT,
  `des_tipo_aluno` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_tipo_aluno`),
  UNIQUE INDEX `des_tipo_aluno_UNIQUE` (`des_tipo_aluno` ASC) VISIBLE,
  UNIQUE INDEX `id_tipo_aluno_UNIQUE` (`id_tipo_aluno` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agil`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agil`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `agil`.`tipo_usuario` (
  `id_tipo` INT(11) NULL DEFAULT NULL,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  INDEX `fk_id_tipo_idx` (`id_tipo` ASC) VISIBLE,
  INDEX `fk_id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_id_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `agil`.`tipo` (`id_tipo`),
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `agil`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agil`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agil`.`usuario` ;

CREATE TABLE IF NOT EXISTS `agil`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL DEFAULT NULL,
  `cpf` INT(11) NULL DEFAULT NULL,
  `passaporte` INT(11) NULL DEFAULT NULL,
  `matricula` INT(11) NULL DEFAULT NULL,
  `des_email` VARCHAR(60) NULL DEFAULT NULL,
  `num_celular` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
